const pokemonList = [
  { 
    id: 1,
    name: 'Bulbasaur',
    type: 'Grass',
    averageWeight: {value: 69, measurementUnit: 'Kg'},
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/1.png', 
  },
  { 
    id: 4,
    name: 'Charmander',
    type: 'Fire',
    averageWeight: {value: 85, measurementUnit: 'Kg'},
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/4.png', 
  },
  { 
    id: 5,
    name: 'Charmeleon',
    type: 'Fire',
    averageWeight: {value: 190, measurementUnit: 'Kg'},
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/5.png', 
  },
  { 
    id: 7,
    name: 'Squirtle',
    type: 'Water',
    averageWeight: {value: 90, measurementUnit: 'Kg'},
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/7.png', 
  },
  { 
    id: 8,
    name: 'Wartortle',
    type: 'Water',
    averageWeight: {value: 225, measurementUnit: 'Kg'},
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/8.png', 
  },
  { 
    id: 9,
    name: 'Blastoise',
    type: 'Water',
    averageWeight: {value: 85.5, measurementUnit: 'Kg'},
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/9.png', 
  },
  { 
    id: 10,
    name: 'Caterpie',
    type: 'Bug',
    averageWeight: {value: 2.9, measurementUnit: 'Kg'},
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/10.png', 
  },
  { 
    id: 11,
    name: 'Metapod',
    type: 'Bug',
    averageWeight: {value: 9.9, measurementUnit: 'Kg'},
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/11.png', 
  },
  { 
    id: 19,
    name: 'Rattata',
    type: 'Normal',
    averageWeight: {value: 3.5, measurementUnit: 'Kg'},
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/19.png', 
  },
  { 
    id: 20,
    name: 'Raticate',
    type: 'Normal',
    averageWeight: {value: 18.5, measurementUnit: 'Kg'},
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/20.png', 
  },
  { 
    id: 23,
    name: 'Ekans',
    type: 'Poison',
    averageWeight: {value: 6.9, measurementUnit: 'Kg'},
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/23.png', 
  },
  { 
    id: 24,
    name: 'Arbok',
    type: 'Poison',
    averageWeight: {value: 65, measurementUnit: 'Kg'},
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/24.png', 
  },
  { 
    id: 25,
    name: 'Pikachu',
    type: 'Electric',
    averageWeight: {value: 6, measurementUnit: 'Kg'},
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/25.png', 
  },
  { 
    id: 26,
    name: 'Raichu',
    type: 'Electric',
    averageWeight: {value: 30, measurementUnit: 'Kg'},
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/26.png', 
  },
];

export default pokemonList;